import {StyleSheet, Platform, Dimensions} from 'react-native';
import {size, family} from '../fonts';
import {colors} from '../theme';

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  circle: {
    width: 35,
    height: 35,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  inputsty1: {
    borderWidth: 1.5,
    borderColor: colors.grey,
    paddingHorizontal: 15,
    borderRadius: 8,
    width: '100%',
    height: 50,
    alignSelf: 'center',
    marginBottom: 8,
    backgroundColor:'rgba(255, 255, 255, 0.7)'
  },
  bell_count: {
    minWidth: 20,
    minHeight: 15,
    borderRadius: 10,
    backgroundColor: colors.blue,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: -15,
    left: 1,
  },
  flex: {
    flex: 1,
  },
  icon: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  thumbnailSty: {
    width: 80,
    height: 80,
    borderRadius: 10,
  },
  txbold: {
    fontFamily: family.semibold,
  },
  borderStyle: {borderWidth: 1, borderColor: colors.grey},
  row: {flexDirection: 'row'},

  pv20: {paddingVertical: 20},

  pd20: {padding: 20},
  pd40: {padding: 40},
  pd10: {padding: 10},
  pd_H10: {paddingHorizontal: 10},
  pdT0: {paddingTop: 0},
  pd_H20: {paddingHorizontal: 20},
  pd_H40: {paddingHorizontal: 40},
  mt_v: {marginVertical: 10},
  mt_B: {marginBottom: 10},
  mt_B10: {marginBottom: 10},
  ml_5: {marginLeft: 15},
  ml_05: {marginLeft: -4},
  ml_15: {marginLeft: 10},
  ml_30: {marginLeft: 40},
  mt_t7: {marginTop: -5},
  mt_t8: {marginTop: 5},
  mt_t10: {marginTop: 10},
  mt_t30: {marginTop: 30},
  mt_t1: {marginTop: 1},
  mt_t20: {marginTop: 20},
  mt_t60: {marginTop: 60},
  mt_t200: {marginTop: 200},
  mt_t300: {marginTop: 300},
  mt_t150: {marginTop: 150},
  mt_t150: {marginTop: 150},
  mt_t140: {marginTop: 140},
  mt_t100: {marginTop: 100},
  mt_t_10: {marginTop: -6},
  mh_10: {marginHorizontal: 10},
  mr_10: {marginRight: 15},
  mt_50: {marginTop: '50%'},

  wdh60: {width: '60%'},
  wdh40: {width: '40%'},
  wdh20: {width: '20%'},
  wdh30: {width: '30%'},
  wdh10: {width: '10%'},
  wdh15: {width: '15%'},
  wdh55: {width: '55%'},
  wdh53: {width: '51%'},
  wdh70: {width: '70%'},
  wdh50: {width: '50%'},
  wdh48: {width: '48%'},
  wdh80: {width: '80%'},
  wdh75: {width: '75%'},
  wdh79: {width: '79%'},
  wdh90: {width: '90%'},
  wdh65: {width: '65%'},
  wdh85: {width: '85%'},
  wdh45: {width: '45%'},
  mr30: {marginRight: '30%'},

  center: {justifyContent: 'center', alignItems: 'center', flex: 1},
  align_C: {alignItems: 'center'},
  align_E: {alignItems: 'flex-end'},
  align_S: {alignItems: 'flex-start'},
  justify_C: {justifyContent: 'center'},
  justify: {justifyContent: 'flex-end'},
  justify_S: {justifyContent: 'space-between'},
  justify_A: {justifyContent: 'space-around'},
  justify_E: {justifyContent: 'space-evenly'},

  txAlignC: {textAlign: 'center'},
  txAlignJ: {textAlign: 'justify'},
  txAlignR: {textAlign: 'right'},
  txAlignL: {textAlign: 'left'},

  txCap: {textTransform: 'capitalize'},
  txUpr: {textTransform: 'uppercase'},

  txDecor: {textDecorationLine: 'underline'},
  txColor: {
    color: colors.black,
  },
  tx10: {
    fontSize: 10,
    color: colors.black,
    fontFamily: family.regular,
  },
  tx12: {
    fontSize: size.label,
    color: colors.black,
    fontFamily: family.regular,
  },

  tx13: {
    fontSize: size.subtitle,
    color: colors.black,
    fontFamily: family.regular,
  },
  txradio: {
    fontSize: size.subtitle,
    color: colors.black,
    fontFamily: family.regular,
    textAlign: 'justify',
    // letterSpacing: 1,
  },
  headingtxt: {
    height: 42,
    width: 100,
    opacity: 0.9,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 2,
    borderRadius: 5,
    backgroundColor: colors.indian_red,
    margin: 1,
  },
  tx14No: {
    fontSize: 16,
    color: colors.black,
    fontFamily: family.regular,
    textAlign: 'justify',
  },
  htxt: {
    textAlign: 'center',
    color: 'white',
    fontSize: 16,
    letterSpacing: 0.3,
  },
  tx14: {
    fontSize: size.subtitle,
    color: colors.black,
    fontFamily: family.regular,
    textAlign: 'justify',
  },
  tx14_B: {
    fontSize: size.subtitle,
    color: colors.black,
    fontFamily: family.semibold,
    textAlign: 'justify',
    letterSpacing: 0.6,
  },
  temsCondition: {
    fontSize: 13,
    color: colors.black,
    fontFamily: family.semibold,
    textAlign: 'justify',
    // letterSpacing: 0.6,
  },
  tx14_C: {
    fontSize: size.subtitle,
    fontFamily: family.semibold,
    textAlign: 'justify',
    letterSpacing: 0.6,
  },
  txlocation: {
    fontSize: size.location,
    color: colors.black,
    fontFamily: family.regular,
    textAlign: 'justify',
  },
  tx18: {
    fontSize: size.subheading,
    color: colors.black,
    fontFamily: family.medium,
    textAlign: 'justify',
  },
  tx16: {
    fontSize: size.title,
    color: colors.black,
    fontFamily: family.semibold,
    lineHeight: 24,
    letterSpacing: 0.3,
  },

  headerLeftTitle: {
    fontSize: size.title,
    color: colors.PRIMARY_LIGHT_TEXT,
    fontFamily: family.regular,
    fontWeight:'600',
    lineHeight: 21.82,
    letterSpacing: 0.3,
  },

  headerCourceTitle: {
    fontSize: size.subtitle,
    color: colors.PRIMARY_DARK,
    fontFamily: family.medium,
    fontWeight:'600',
    lineHeight: 21.82,
    // letterSpacing: 0.3,
  },

  error: {
    color: colors.danger,
    fontSize: 12,
    marginLeft: 15,
  },

  btntxt: {
    fontSize: size.subtitle,
    color: colors.blue,
    fontFamily: family.medium,
    letterSpacing: 1,
    textAlign: 'center',
  },
  tx20: {
    fontSize: size.heading,
    color: colors.logogreen,
    fontFamily: family.bold,
  },

  txheading: {
    fontSize: size.title,
    color: colors.fontcolor,
    fontFamily: family.bold,
    fontStyle: 'italic',
    fontWeight: '800',
    letterSpacing: 1,
  },
  txheader: {
    fontSize: size.title,
    color: colors.white,
    fontFamily: family.medium,
  },
  tx22: {
    fontSize: 22,
    color: colors.black,
    fontFamily: family.medium,
  },
  logoSty: {
    width: 121,
    height: 76,
    resizeMode: 'contain',
  },

  box: {
    borderWidth: 1.5,
    borderColor: colors.grey,
    paddingHorizontal: 5,
    width: 125,
  },
  inputsty: {
    backgroundColor: colors.BACKGROUD_GREY_COLOR,
    opacity: 0.6,
    borderRadius: 6,
//borderColor:colors.grey,
    paddingHorizontal: 15,

    width: '100%',
    height: 50,
    alignSelf: 'center',
    marginBottom: 8,
  },
  inputDatesty: {
    backgroundColor: colors.white,
    opacity: 0.6,
    borderRadius: 6,
    borderColor:colors.grey,
    paddingHorizontal: 15,
    borderWidth: 1.5,
    width: '100%',
    height: 50,
    alignSelf: 'center',
    marginBottom: 8,
  },
  hardText:{
    fontSize: 48,
    color: colors.white,
    fontFamily: family.semibold,
    lineHeight: 66,
    // letterSpacing: 0.3,
  },
  iconsty: {
    width: 44,
    height: 44,
    resizeMode: 'contain',
  },

  picker_sty: {
    borderWidth: 1,
    borderColor: colors.grey,
    borderRadius: 8,
    marginTop: 5,
  },
  animatedCir_1: {
    // width: 135, height: 135,
    borderRadius: 13,
    borderWidth: 2,
    flexDirection: 'row',
    borderColor: colors.white,
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 15,
    marginBottom: 5,
  },
  mybtn: {
    padding: 5,
    borderRadius: 5,
    backgroundColor: colors.indian_red,
    width: 90,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mybtnbene: {
    padding: 5,
    borderRadius: 5,
    backgroundColor: colors.indian_red,
    width: 190,
    justifyContent: 'center',
    alignItems: 'center',
  },

  card: {
    // width: '100%',
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    // elevation: 100, // For Android shadow
    shadowColor: '#000', // For iOS shadow
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 10,
    // paddingHorizontal: 25,
  },

  cardsty: {
    // backgroundColor: 'white',
    // borderRadius: 10,
    paddingBottom: 30,
    width: '90%',
    // opacity: 0.6,
    // borderWidth: 0.3,
    // borderColor: '#AAA9A9',
    // marginTop: -60,
    // elevation: 1,
    // overflow: 'hidden',
    // flex: 1,
    // justifyContent: 'center',
    // alignItems: 'center',
    // backgroundColor: 'rgba(0, 0, 0, 0.4)',
  },
  modalcardsty: {
    // backgroundColor: 'white',
    // borderRadius: 10,
    paddingBottom: 30,
    width: '100%',
    // height:"50%",
    // opacity: 0.6,
    // borderWidth: 0.3,
    // borderColor: '#AAA9A9',
    // marginTop: -60,
    // elevation: 1,
    // overflow: 'hidden',
    // flex: 1,
    // justifyContent: 'center',
    // alignItems: 'center',
    // backgroundColor: 'rgba(0, 0, 0, 0.4)',
  },
  otpCard: {
    paddingBottom: 30,
    width: '90%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  shadowProp: {
    // shadowColor: colors.black,
    // shadowOffset: {width: 0, height: 1},
    // shadowOpacity: 1,
    // shadowRadius: 10,
  },

  option: {
    flex: 1,
    flexWrap: 'wrap',

    flexDirection: 'row',
  },
  draftBox: {
    marginTop: 10,
    borderLeftWidth: 20,
    padding: 15,
    margin: 6,
    borderRadius: 10,
    // borderColor: colors.grey,
    borderWidth: 0.5,
    backgroundColor: colors.white,
    marginBottom: 10,
  },
  boxsty: {
    padding: 15,
    borderRadius: 10,
    borderColor: colors.grey,
    borderWidth: 0.5,
    backgroundColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
    elevation: 1,
  },
  homeimage: {
    height: 38,
    width: 38,
    marginRight: 15,
  },
  checklistcard: {
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 15,
    borderWidth: 1,
    borderTopColor: colors.grey,
    borderBottomColor: colors.grey,
    borderLeftColor: colors.grey,
    marginVertical: 5,
  },
  checklistoptionContainer: {
    marginTop: 5,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 20,
  },
  headingtxt: {
    height: 42,
    width: 100,
    opacity: 0.9,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 2,
    borderRadius: 5,
    backgroundColor: colors.indian_red,
    margin: 1,
  },
  htxt: {
    textAlign: 'center',
    color: 'white',
    fontSize: 16,
    letterSpacing: 0.3,
  },
  disabledButton: {
    backgroundColor: colors.grey,
  },
  SyncStatusTextColor: {
    inprogess: colors.orange,
    completed: colors.green,
    error: colors.red,
  },
  privacyTxt: {
    fontSize: size.label,
    color: 'grey',
    fontFamily: family.regular,
    textDecorationLine: 'underline',
  },
});
