import {StyleSheet, Platform, Dimensions, StatusBar} from 'react-native';
import {size, family, SIZES, FONTSIZE, WEIGHT, MARGIN} from '../fonts';
import {colors} from '../theme';
const screenWidth = Dimensions.get('window').width;
export default StyleSheet.create({
  container: {
    flex: 1,
  },
  circle: {
    width: 35,
    height: 35,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bell_count: {
    minWidth: 20,
    minHeight: 15,
    borderRadius: 10,
    backgroundColor: colors.blue,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: -15,
    left: 1,
  },
  flex: {
    flex: 1,
  },
  icon: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  centerAlign:{
    alignItems: 'center',
  },
  thumbnailSty: {
    width: 80,
    height: 80,
    borderRadius: 10,
  },
  txbold: {
    fontFamily: family.semibold,
  },
  borderStyle: {borderWidth: 1, borderColor: colors.grey},
  row: {flexDirection: 'row'},

  pv20: {paddingVertical: 20},

  pd20: {padding: 20},
  pd40: {padding: 40},
  pd10: {padding: 10},
  pd_H10: {paddingHorizontal: 10},
  pdT0: {paddingTop: 0},
  pd_H20: {paddingHorizontal: 20},
  pd_H40: {paddingHorizontal: 40},
  mt_v: {marginVertical: 10},
  mt_B: {marginBottom: 10},
  mt_B10: {marginBottom: 10},
  ml_5: {marginLeft: 15},
  ml_05: {marginLeft: -4},
  ml_15: {marginLeft: 10},
  ml_30: {marginLeft: 40},
  mt_t7: {marginTop: -5},
  mt_t8: {marginTop: 5},
  mt_t10: {marginTop: 10},
  mt_t30: {marginTop: 30},
  mt_t1: {marginTop: 1},
  mt_t20: {marginTop: 20},
  mt_t60: {marginTop: 60},
  mt_t200: {marginTop: 200},
  mt_t150: {marginTop: 150},
  mt_t150: {marginTop: 150},
  mt_t140: {marginTop: 140},
  mt_t100: {marginTop: 100},
  mt_t300: {marginTop: 330},
  mt_t_10: {marginTop: -6},
  mh_10: {marginHorizontal: 10},
  mr_10: {marginRight: 15},
  mt_50: {marginTop: '50%'},

  wdh60: {width: '60%'},
  wdh40: {width: '40%'},
  wdh20: {width: '20%'},
  wdh30: {width: '30%'},
  wdh10: {width: '10%'},
  wdh15: {width: '15%'},
  wdh55: {width: '55%'},
  wdh53: {width: '51%'},
  wdh70: {width: '70%'},
  wdh50: {width: '50%'},
  wdh48: {width: '48%'},
  wdh80: {width: '80%'},
  wdh75: {width: '75%'},
  wdh79: {width: '79%'},
  wdh90: {width: '90%'},
  wdh65: {width: '65%'},
  wdh85: {width: '85%'},
  wdh45: {width: '45%'},
  mr30: {marginRight: '30%'},

  center: {justifyContent: 'center', alignItems: 'center', flex: 1},
  couseContainer: {alignItems: 'center', flex: 1},
  align_C: {alignItems: 'center'},
  align_E: {alignItems: 'flex-end'},
  align_S: {alignItems: 'flex-start'},
  justify_C: {justifyContent: 'center'},
  justify: {justifyContent: 'flex-end'},
  justify_S: {justifyContent: 'space-between'},
  justify_A: {justifyContent: 'space-around'},
  justify_E: {justifyContent: 'space-evenly'},

  txAlignC: {textAlign: 'center'},
  txAlignJ: {textAlign: 'justify'},
  txAlignR: {textAlign: 'right'},
  txAlignL: {textAlign: 'left'},

  txCap: {textTransform: 'capitalize'},
  txUpr: {textTransform: 'uppercase'},

  txDecor: {textDecorationLine: 'underline'},
  txColor: {
    color: colors.black,
  },
  tx10: {
    fontSize: 10,
    color: colors.black,
    fontFamily: family.regular,
  },
  tx12: {
    fontSize: size.label,
    color: colors.black,
    fontFamily: family.regular,
  },

  tx13: {
    fontSize: size.subtitle,
    color: colors.black,
    fontFamily: family.regular,
  },
  txradio: {
    fontSize: size.subtitle,
    color: colors.black,
    fontFamily: family.regular,
    textAlign: 'justify',
    // letterSpacing: 1,
  },
  headingtxt: {
    height: 42,
    width: 100,
    opacity: 0.9,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 2,
    borderRadius: 5,
    backgroundColor: colors.indian_red,
    margin: 1,
  },
  tx14No: {
    fontSize: 16,
    color: colors.black,
    fontFamily: family.regular,
    textAlign: 'justify',
  },
  htxt: {
    textAlign: 'center',
    color: 'white',
    fontSize: 16,
    letterSpacing: 0.3,
  },
  tx14: {
    fontSize: size.subtitle,
    color: colors.black,
    fontFamily: family.regular,
    textAlign: 'justify',
  },
  tx14_B: {
    fontSize: size.subtitle,
    color: colors.black,
    fontFamily: family.semibold,
    textAlign: 'justify',
    letterSpacing: 0.6,
  },
  temsCondition: {
    fontSize: 13,
    color: colors.black,
    fontFamily: family.semibold,
    textAlign: 'justify',
    // letterSpacing: 0.6,
  },
  tx14_C: {
    fontSize: size.subtitle,
    fontFamily: family.semibold,
    textAlign: 'justify',
    letterSpacing: 0.6,
  },
  txlocation: {
    fontSize: size.location,
    color: colors.black,
    fontFamily: family.regular,
    textAlign: 'justify',
  },
  tx18: {
    fontSize: size.subheading,
    color: colors.black,
    fontFamily: family.medium,
    textAlign: 'justify',
  },
  tx16: {
    fontSize: size.title,
    color: colors.black,
    fontFamily: family.semibold,
    lineHeight: 24,
    letterSpacing: 0.3,
  },

  headerLeftTitle: {
    fontSize: size.title,
    color: colors.PRIMARY_LIGHT_TEXT,
    fontFamily: family.regular,
    fontWeight:'600',
    lineHeight: 21.82,
    letterSpacing: 0.3,
  },

  headerCourceTitle: {
    fontSize: size.subtitle,
    color: colors.PRIMARY_DARK,
    fontFamily: family.medium,
    fontWeight:'600',
    lineHeight: 21.82,
    // letterSpacing: 0.3,
  },

  error: {
    color: colors.danger,
    fontSize: 12,
    marginLeft: 15,
  },

  btntxt: {
    fontSize: size.subtitle,
    color: colors.blue,
    fontFamily: family.medium,
    letterSpacing: 1,
    textAlign: 'center',
  },
  tx20: {
    fontSize: size.heading,
    color: colors.logogreen,
    fontFamily: family.bold,
  },

  txheading: {
    fontSize: size.title,
    color: colors.fontcolor,
    fontFamily: family.bold,
    fontStyle: 'italic',
    fontWeight: '800',
    letterSpacing: 1,
  },
  txheader: {
    fontSize: size.title,
    color: colors.white,
    fontFamily: family.medium,
  },
  tx22: {
    fontSize: 22,
    color: colors.black,
    fontFamily: family.medium,
  },
  logoSty: {
    width: 121,
    height: 76,
    resizeMode: 'contain',
  },

  box: {
    borderWidth: 1.5,
    borderColor: colors.grey,
    paddingHorizontal: 5,
    width: 125,
  },
  inputsty: {
    backgroundColor: colors.PRIMARY_TRANSPARENT_BLACK,
    opacity: 0.6,
    borderRadius: 6,
//borderColor:colors.grey,
    paddingHorizontal: 15,

    width: '100%',
    height: 50,
    alignSelf: 'center',
    marginBottom: 8,
  },
  inputDatesty: {
    backgroundColor: colors.white,
    opacity: 0.6,
    borderRadius: 6,
    borderColor:colors.grey,
    paddingHorizontal: 15,
    borderWidth: 1.5,
    width: '100%',
    height: 50,
    alignSelf: 'center',
    marginBottom: 8,
  },
  hardText:{
    fontSize: 48,
    color: colors.white,
    fontFamily: family.semibold,
    lineHeight: 66,
    // letterSpacing: 0.3,
  },
  iconsty: {
    width: 44,
    height: 44,
    resizeMode: 'contain',
  },

  picker_sty: {
    borderWidth: 1,
    borderColor: colors.grey,
    borderRadius: 8,
    marginTop: 5,
  },
  animatedCir_1: {
    // width: 135, height: 135,
    borderRadius: 13,
    borderWidth: 2,
    flexDirection: 'row',
    borderColor: colors.white,
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 15,
    marginBottom: 5,
  },
  mybtn: {
    padding: 5,
    borderRadius: 5,
    backgroundColor: colors.indian_red,
    width: 90,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mybtnbene: {
    padding: 5,
    borderRadius: 5,
    backgroundColor: colors.indian_red,
    width: 190,
    justifyContent: 'center',
    alignItems: 'center',
  },

  card: {
    // width: '100%',
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    // elevation: 100, // For Android shadow
    shadowColor: '#000', // For iOS shadow
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 10,
    // paddingHorizontal: 25,
  },

  cardsty: {
    paddingBottom: 30,
    width: '90%',
    marginTop:50
  },
  fcardsty: {
    paddingBottom: 30,
    width: '90%',
    marginTop:20
  },
  modalcardsty: {
    paddingBottom: 30,
    width: '100%',
  },
  otpCard: {
    paddingBottom: 30,
    width: '90%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  shadowProp: {
  },

  option: {
    flex: 1,
    flexWrap: 'wrap',

    flexDirection: 'row',
  },
  draftBox: {
    marginTop: 10,
    borderLeftWidth: 20,
    padding: 15,
    margin: 6,
    borderRadius: 10,
    // borderColor: colors.grey,
    borderWidth: 0.5,
    backgroundColor: colors.white,
    marginBottom: 10,
  },
  boxsty: {
    padding: 15,
    borderRadius: 10,
    borderColor: colors.grey,
    borderWidth: 0.5,
    backgroundColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
    elevation: 1,
  },
  homeimage: {
    height: 38,
    width: 38,
    marginRight: 15,
  },
  checklistcard: {
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 15,
    borderWidth: 1,
    borderTopColor: colors.grey,
    borderBottomColor: colors.grey,
    borderLeftColor: colors.grey,
    marginVertical: 5,
  },
  checklistoptionContainer: {
    marginTop: 5,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 20,
  },
  headingtxt: {
    height: 42,
    width: 100,
    opacity: 0.9,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 2,
    borderRadius: 5,
    backgroundColor: colors.indian_red,
    margin: 1,
  },
  htxt: {
    textAlign: 'center',
    color: 'white',
    fontSize: 16,
    letterSpacing: 0.3,
  },
  disabledButton: {
    backgroundColor: colors.grey,
  },
  SyncStatusTextColor: {
    inprogess: colors.orange,
    completed: colors.green,
    error: colors.red,
  },
  privacyTxt: {
    fontSize: size.label,
    color: 'grey',
    fontFamily: family.regular,
    textDecorationLine: 'underline',
  },
  HoleListContatiner: {
    width: '100%',
    height:"100%",
    backgroundColor:'#FFF',
  },
   metricBox: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: 15,
    height: 47,
  },
  clubTitle: {
    color: '#1D1A0C',
    fontSize: 14, 
    fontFamily: family.medium,
    // fontWeight: '600',
  },
  imageContainer: {
    borderWidth: 1,
    elevation: 1,
    borderColor: '#FFF',
    alignItems: 'center',
    marginTop: 15,
    marginHorizontal: 15,
    backgroundColor: '#FFF',
    borderRadius: 12,
  },
  imageGolf: {
    width: screenWidth - 30,
    borderRadius: 12,
    height: 172,
  },
  title: {
    fontSize: FONTSIZE.FONTSIZE_13,
    color: colors.PRIMARY_LIGHT_TEXT,
    fontFamily: family.regular,
    fontWeight: WEIGHT.WEIGHT_400,
  },
  paymentView: {
    margin: MARGIN.MARGIN_15,
    paddingVertical: SIZES.SIZES_26,
    backgroundColor: colors.BACKGROUD_ICON_COLOR,
    padding: SIZES.SIZES_20,
    borderRadius: SIZES.SIZES_6,
  },
  radioparentView: {
    // backgroundColor:'red',
    marginVertical: SIZES.SIZES_10,
  },

  cardInput: {
    marginVertical: 5,
    borderColor: colors.grey,
    // backgroundColor:'#FFF',
    borderWidth: 0.5,
  },

  label: {
    fontSize: 16,
    marginBottom: 10,
  },
  input: {
    // height: 32,
    borderWidth: 0.5,
    borderColor: '#E6E6E6',
    backgroundColor: '#FFF',
    borderRadius: 4,
    paddingHorizontal: 10,
    marginBottom: 20,
    fontSize: 13,
    color: colors.PRIMARY_DARK,
    fontFamily: family.regular,
  },

  optionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    // paddingVertical: SIZES.SIZES_5,
    marginTop: 15,
  },
  radioCircle: {
    height: SIZES.SIZES_16,
    width: SIZES.SIZES_16,
    borderRadius: SIZES.SIZES_8,

    borderWidth: SIZES.SIZES_2,
    borderColor: colors.BORDER_GREY_COLOR,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedCircle: {
    width: SIZES.SIZES_8,
    height: SIZES.SIZES_8,
    borderRadius: SIZES.SIZES_4,
    backgroundColor: colors.BLUE_COLOR,
  },
  cardInfo: {
    // backgroundColor:'red',
    left: 10,
    flex: 1,
  },
  cardTitle: {
    fontSize: SIZES.SIZES_13,
    fontWeight: WEIGHT.WEIGHT_500,
    color: colors.PRIMARY_DARK,
  },
  cardDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 5,
  },
  cardNumber: {
    fontSize: FONTSIZE.FONTSIZE_11,
    color: colors.PRIMARY_LIGHT_TEXT,
    fontFamily: family.regular,
    fontWeight: WEIGHT.WEIGHT_400,
    // marginRight: 10,
  },
  cardLogo: {
    width: 20,
    height: 20,
    marginRight: 10,
  },
  cardHolder: {
    fontSize: FONTSIZE.FONTSIZE_11,
    color: colors.PRIMARY_LIGHT_TEXT,
    fontFamily: family.regular,
    fontWeight: WEIGHT.WEIGHT_400,
  },
  addNewText: {
    fontSize: SIZES.SIZES_13,
    fontWeight: WEIGHT.WEIGHT_500,
    color: colors.PRIMARY_DARK,
    left: 10,
  },communityitemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.8)', // Transparent background for list items
    borderRadius: 10,
    marginBottom: 10,
    padding: 10,
    //elevation: 1,
  },
  communityavatar: {
    width: 50,
    height: 50,
    borderRadius: 6,
  },
  communitytextContainer: {
    flex: 1,
    marginLeft: 10,
  },
  communityname: {
    // fontWeight: 'bold',
    fontSize: 16,
    color:'#1D1A0C'
  },
  communitylocation: {
    color: '#A9A9A9',
  },
  communityfollowersContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  communityfollowers: {
    marginLeft: 5,
    color: '#A9A9A9',
  }, listcontainer: {
    flex: 1,
    marginTop: StatusBar.currentHeight || -65,
  },
  listoverlay: {
    ...StyleSheet.absoluteFillObject, // Fills the entire screen
    backgroundColor: 'rgba(255, 255, 255, 0.4)', // Apply the opacity here
  },
  listitem: {
    backgroundColor: '#f9c2ff',
    padding: 20,
    marginVertical: 8,
    marginHorizontal: 16,
  },
  listtitle: {
    fontSize: 32,
  },
  listsortBtn: {
    width: 50,
    height: 50,
    marginLeft: 10,
    backgroundColor: colors.blue,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  listinputContainer: {
    flex: 1,
    height: 50,
    borderRadius: 10,
    flexDirection: 'row',
    backgroundColor: colors.grey,
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  listsearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    borderRadius: 8,
    paddingHorizontal: 15,
    height: 50,
    margin: 20,
  },
  listinputStyle: {
    flex: 1,
    padding: 10,
    fontSize: 16,
    color: '#000',
  },
  listiconStyle: {
    marginLeft: 10,
  },

  listbackgroundImage: {
    flex: 1,
    resizeMode: 'cover',
  },
  listlistContainer: {
    padding: 1,
  },
  pcontainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  pprofileContainer: {
    alignItems: 'center',
    marginTop: 30,
    position: 'relative',
  },

  pinfoBoxContainer: {
    backgroundColor: colors.PRIMARY_BUTTON,
    width: '90%',
    // backgroundColor:'red',
    borderRadius: 8,
    paddingTop: 90, // To make space for the profile image
    paddingBottom: 10,
    paddingHorizontal: 20,
    marginTop: -80, // This brings the avatar on top of the box
    alignItems: 'center',
    // zIndex: 0,
  },
  pname: {
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: 10,
    color: '#333',
  },
  plocation: {
    fontSize: 16,
    textAlign: 'center',
    color: '#888',
    marginBottom: 20,
  },
  pinfoContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },

  pavatarContainer: {
    alignItems: 'center',
    zIndex: 1,
  },
  pprofileImage: {
    width: 156,
    height: 156,
    borderRadius: 78,
    borderWidth: 3,
    borderColor: '#fff',
  },
  pcameraIcon: {
    position: 'absolute',
    top: '49%',
  },
  ppanelHeader: {
    alignItems: 'center',
  },
  ppanelHandle: {
    width: 40,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#00000040',
    marginBottom: 10,
  },
  pheader: {
    flexDirection: 'row',
    padding: 10,
  },
  ppanelTitle: {
    fontSize: 27,
    height: 35,
  },
  ppanelSubtitle: {
    fontSize: 14,
    color: 'gray',
    height: 30,
    marginBottom: 10,
  },
  ppanelButton: {
    padding: 13,
    borderRadius: 10,
    backgroundColor: colors.PRIMARY_BUTTON,
    alignItems: 'center',
    marginVertical: 7,
  },
  ppanelButtonTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: 'white',
  },
  ppanel: {
    padding: 20,
    backgroundColor: '#FFFFFF',
    paddingTop: 20,
  },
});
