// export const ENUM = {
//   Checklist: {
//     VHSND: 'VHSND',
//     GODHB: 'GODHB',
//     ANNAP: 'ANNAP',
//     WAJAND: 'WAJAND',
//     FACILITYV: 'FACILITYV',
//     BENEFICARIES_H2H_MONITORING: 'BENEFICARIES_H2H_MONITORING',
//     BASELINE: 'BASELINE',
//     GALIDRAA:'GALIDRAA',
//     SELF_ASSESSMENT_HINDI:'SELF_ASSESSMENT_HINDI'
//   },
//   ChecklistGroup: {
//     H2H_MON_COMPLEMENTARY_FEEDING: 'H2H_MON_COMPLEMENTARY_FEEDING',
//   },
//   ChecklistGroup: {
//     H2H_MON_COMPLEMENTARY_FEEDING: 'H2H_MON_COMPLEMENTARY_FEEDING',
//   },
//   Status: {
//     DRAFT: 'DRAFT',
//     SUBMIT: 'SUBMIT',
//     HEADERSUBMIT: 'SUBMITTED',
//   },
//   ResponseType: {
//     BOOLEAN: 1,
//     NUMBER: 2,
//     TEXT: 3,
//     AWC_CODE: 4,
//     AWW_NAME: 5,
//     VHSND_NAME: 6,
//     FACILITY_NAME: 7,
//     FACILITY_TYPE: 8,
//     FEEDING_OPTIONS: 9,
//     VILLAGE_NAME: 10,
//     BOOL_WITH_DONT_KNOW: 11,
//     DATE: 12,
//     GENDER: 13,
//     FIRST_BREAST_FEED: 14,
//     BREAST_FEED_AGE_LIMIT: 15,
//     MEAL_FREQUENCY: 16,
//     NO_RESPONSE: 17,
//     MONTH_MEAL_FREQUENCY: 18,
//     PHONE_NUMBER: 19,
//     IMAGE: 27,
//   },
//   RenderType: {
//     RADIO_BUTTON: 'RADIO_BUTTON',
//     CHECKBOX: 'CHECKBOX',
//     CHECKBOX_MULTI_SELECT: 'CHECKBOX_MULTI_SELECT',
//     IMAGE: 'IMAGE',
//     DROPDOWN: 'DROPDOWN',
//     DROPDOWN_MULTI_SELECT: 'DROPDOWN_MULTI_SELECT',
//     ITEM: 'ITEM',
//     ITEM_MULTI_SELECT: 'ITEM_MULTI_SELECT',
//     COUNER: 'COUNER', //counter*
//     TEXTBOX: 'TEXTBOX',
//     TEXTBOX_NUMBER: 'TEXTBOX_NUMBER',
//     DATE: 'DATE',
//     NONE: 'NONE',
//   },
//   BooleanValues: {
//     YES: 'Yes',
//     NO: 'No',
//   },
//   BOOL_WITH_DONT_KNOW_Values: {
//     YES: 'Yes',
//     NO: 'No',
//     DontKnow: 'Don`t Know',
//   },

//   SERVERSTATUS: {
//     INPROGRESS: 'IN_PROGRESS',
//     NOTSTARTED: 'NOT_STARTED',
//     COMPLETED: 'COMPLETED',
//     FAILED: 'FAILED',
//   },
//   STATICKEYWORDS: {
//     Current_Month: 'Current Month: ',
//     VIEW_MORE: 'View More .....',
//     RECENT_DRAFTS: 'Recent Drafts',
//     PROFILE: 'Profile',
//     NAME: 'Name',
//     ENTER_NAME: 'Enter Name',
//     EMAIL: 'Email',
//     ENTER_EMAIL: 'Enter Email',
//     MOBILE_NUMBER: 'Mobile Number',
//     ENTER_MOBILE_NUMBER: 'Enter Mobile Number',
//     ENTER_ROLE: 'Enter Role',
//     ROLE: 'Role',
//     ENTER_LOCATION: 'Enter location',
//     LOCATION: 'Location',
//     CLICK_TO_CHANGE_PASSWORD: 'Click to Change Password',
//     SELF_ASSESSMENT_HINDI:'SELF_ASSESSMENT_HINDI'
//   },
//   QuestionEnum: {
//     H2H_MON_CHILD_IDENTIFICATION_DATE_OF_BIRTH:
//       'H2H_MON_CHILD_IDENTIFICATION_DATE_OF_BIRTH',
//   },
//   ShortName: {
//     H2H_MON_CHILD_IDENTIFICATION_DATE_OF_BIRTH: 'DOB',
//     H2H_MON_CHILD_IDENTIFICATION_NAME_OF_THE_MOTHER: 'Mother Name',
//     H2H_MON_CHILD_IDENTIFICATION_NAME_OF_THE_CHILD: 'Child Name',
//   },
// };
