const colors = {
  danger: 'red',
  black: '#000',
  white: '#fff',
  skyblue: '#80CDDB',
  logogreen: '#37bd59',
  fontcolor: 'rgba(0, 102, 102, 1)',
  grey: '#ccc',
  yellow: '#FFFF00',
  primary: 'yellow',
  lightText: '#777',
  blue: '#050448',
  red: '#AF0000',
  pink: '#EF5DA8',
  bcolor: '#ffffff',
  purple: '#AEAFF7',
  lightBlue: '#1A1881',
  blurlightblue: '#7EC8E3',
  orange: '#F09E54',
  footer_bg: '#020074',
  link: '#1F90A5',
  card_border: '#4FE3FE',
  drawerCircle: '#16A9B1A1',
  textBox: '#252836',
  dashboard_bg: '#14243E',
  circle_1: '#37bd59',
  circle_2: '#4A9CB9',
  warning: '#F8A435',
  frozy: '#D3FFF5',
  lightFrozy: '#02BD94',
  lightgrey: '#3E3E3E',
  indian_red: '#A4353D',
  green: '#95C11E',
  BACKGROUD_ICON_COLOR: '#f5f6f7',
  ICON_GREY: '#748c94',
  DARK_GREY: '#484848',
  PRIMARY_DARK: '#1D1A0C',
  PRIMARY_BUTTON: '#0077B6',
  PRIMARY_SMALL_TEXT: '#3A3A3A',
  PRIMARY_SOLID_TEXT: '#FF3B30',
  PRIMARY_LIGHT_TEXT: '#7B7887',
  PRIMARY_BLUE_TEXT: '#050448',
  PRIMARY_TRANSPARENT_BLACK: '#000000',
  LIST_TEXT_COLOR: '#A9A9A9',
  SUCCESS_GREEN:'#248A3D',
  BACKGROUD_GREY_COLOR:'#97D0A533',
  BORDER_GREY_COLOR:'#D6D6D6',
  BLUE_COLOR:'#002D62',
  
};

const images = {
  scanner: require('../../images/scanner.png'),

  // cource screen Icon
  golfPoint: require('../../images/golfPoint.png'),
  golfPinShot: require('../../images/golfPinShot.png'),
  Add: require('../../images/Add.png'),
  Remove: require('../../images/delete.png'),
  delete: require('../../images/delete.png'),
  

  splashBG: require('../../images/splash-background.png'),
  splashLogo: require('../../images/splash-items.png'),

  loginBG: require('../../images/bg5.png'),
  loginLogo: require('../../images/acecamlogo.png'),
  menu: require('../../images/menu.png'),
  logo: require('../../images/logo.png'),
  SplashScreen: require('../../images/backgroungimg.png'),
  Nodatafound: require('../../images/Nodatafound.png'),
  communitybg: require('../../images/communitybg.png'),
  Success: require('../../images/success.png'),
  house: require('../../images/house.png'),
  user: require('../../images/userimg.png'),
  logoBuddha: require('../../images/b10.png'),
  golfVedio: require('../../images/golfVedio.png'),
  dropDown : require('../../images/dropdown.png'),
  bg1 : require('../../images/bg1.png'),
  // usgaGhin: require('../../images/USGA.png'),
  // golfTrophy: require('../../images/trophy.png'),
  chalisa: require('../../images/chalisa.png'),
  pujapath: require('../../images/pujapath.png'),
  stotra: require('../../images/stotra.png'),
  stuti: require('../../images/stuti.png'),
  vidhi: require('../../images/vidhi.png'),
  bhakti: require('../../images/bhakti.png'),
  aarti: require('../../images/aarti.png'),
  granth: require('../../images/granth.png'),
  golfVedio: require('../../images/golfVedio.png'),
  closeIcon: require('../../images/close.png'),
  // video: '../../images/video.mp4',

  googlelogo: '../../images/glogo.png',
  instagramlogo: '../../images/ilogo.png',
  Instagram: '../../images/Instagram.png',
  twitter: '../../images/twitter.png',
  Facebook: '../../images/Facebook.png',
  TikTok: '../../images/TikTok.png',
  Google: '../../images/Google.png',
  LogoScan:'../../images/LogoScan.png',

  //Home Screen Icons
  LeftCourceImg: require('../../images/LeftCourceImg.png'),
  backIconHeader: require('../../images/backIconHeader.png'),
};

const NAVIGATION = {
  TO_LOGIN: 'Login',
  TO_EDIT_PROFILE: 'EditProfile',
  TO_PROFILE: 'EditProfile',
  TO_FORGET_PASSWORD: 'Verifyemail',
  TO_SIGNUP: 'Signup',
  TO_OTP_SCREEN: 'otp',
  TO_CHANGE_PASSWORD: 'Changepassword',
  TO_SUCCESS_SCREEN: 'SuccessScreen',
};

const APP_TEXT = {
  // RESET PASSWORD OTP SCREEN - otp.js
  SPLASH_TEXT: 'Capturing Golf’s Greatest Shots',
  SPLASH_APP_NAME: 'AceCam',

  RESET_YOUR_PASSWORD: 'OTP Verification',
  OTP_SENT_TO: 'Enter the OTP sent to ',
  OTP_VALID_FOR: 'OTP is valid for 5 minutes',
  DIDNT_RECIEVE_OTP: 'Didn’t you receive the OTP? ',
  RESEND_OTP: 'Resend OTP',
  VERIFY_BUTTON: 'Verify Email',
  BACK_TO_LOGIN: 'Back to Login',
  YOU_CAN_RESEND_OTP: 'You can resend OTP in',
  SECONDS: 'seconds',
  HOME: 'Home',
  COMMUNITIES: 'Communities',
  CONTESTS: 'Contests',
  BET_CENTRAL:'Bet Central',
  NOTI:'Notification',
  COURSE:'Course',
  COMMUNITY: 'Community',
  PROFILE: 'Profile',
  PLAY: 'Play',
  SPLASH_TEXT: 'Capturing Golf’s Greatest Shots',
  SPLASH_APP_NAME: 'AceCam',

  // LOGIN SCREEN - login.js
  LOGIN_OR: '- OR -',
  LOGIN_USERNAME: 'Username',
  LOGIN_PASSWORD: 'Password',
  LOGIN_REMEMBER_ME: 'Remember Me?',
  LOGIN_CONFIRM_PASSWORD: 'Confirm Password',
  LOGIN_LOGIN: 'Login',
  LOGIN_DONT_HAVE_AN_ACCOUNT: 'Don’t have an account? ',
  LOGIN_SIGNUP: 'Sign Up',
  LOGIN_FORGET_PASSWORD: 'Forgot Password',
  SEND_OTP: 'Send OTP',

  // RESET PASSWORD SCREEN - Verifyemail.js
  RESET_PASSWORD: 'Forgot Your Password',
  RESET_YOUR_PASSWORD: 'Reset Your Password',
  EMAIL_PLACEHOLDER: 'Enter Registered Email Id',
  RESET_BUTTON: 'Reset Password',
  SUCCESS: 'SUCCESS',
  PASSWORD_CHANGED: 'Password Changed',

  // REGISTER SCREEN - signup.js
  FIRST_NAME: 'First Name',
  LAST_NAME: 'Last Name',
  USER_NAME: 'Username',
  CONFIRM_PASSWORD: 'Confirm Password',
  DATE_OF_BIRTH: 'Date of Birth',
  EMAIL: 'Email',
  PHONE: 'Phone',
  GHIN: 'GHIN',
  CARD_INFORMATION: 'Card Information',
  CARD_NUMBER: 'Card Number',
  EXPIRE_DATE: 'Expiry Date',
  CVV: 'CVV',
  NAME_ON_CARD: 'Full Name On Card',
  AGREEING_TO: 'Agreeing to',
  TERMS_AND_CONDITION: ' Terms and Conditions',
  OF_THE_CONTEST: ' of the contest',
  CREATE_ACCOUNT: 'Create Account',
  ALREADY_HAVE_ACCOUNT: 'Already have an account?',
};

export {colors, images, APP_TEXT, NAVIGATION};
