const colors = {
  danger: 'red',
  black: '#000',
  white: '#fff',
  skyblue: '#80CDDB',
  logogreen: '#37bd59',
  fontcolor: 'rgba(0, 102, 102, 1)',
  grey: '#ccc',
  yellow: '#FFFF00',
  primary: 'yellow',
  lightText: '#777',
  blue: '#050448',
  red: '#AF0000',
  pink: '#EF5DA8',
  bcolor: '#ffffff',
  purple: '#AEAFF7',
  lightBlue: '#1A1881',
  blurlightblue: '#7EC8E3',
  orange: '#F09E54',
  footer_bg: '#020074',
  link: '#1F90A5',
  card_border: '#4FE3FE',
  drawerCircle: '#16A9B1A1',
  textBox: '#252836',
  dashboard_bg: '#14243E',
  circle_1: '#37bd59',
  circle_2: '#4A9CB9',
  warning: '#F8A435',
  frozy: '#D3FFF5',
  lightFrozy: '#02BD94',
  lightgrey: '#3E3E3E',
  indian_red: '#A4353D',
  green: '#95C11E',
  BACKGROUD_ICON_COLOR: '#f5f6f7',
  ICON_GREY: '#748c94',
  DARK_GREY: '#484848',
  PRIMARY_DARK: '#1D1A0C',
  PRIMARY_BUTTON: '#0077B6',
  PRIMARY_SMALL_TEXT: '#3A3A3A',
  PRIMARY_SOLID_TEXT: '#FF3B30',
  PRIMARY_LIGHT_TEXT: '#7B7887',
  PRIMARY_BLUE_TEXT: '#1E95C1',
  PRIMARY_TRANSPARENT_BLACK: '#000000',
  LIST_TEXT_COLOR: '#A9A9A9',
  SUCCESS_GREEN: '#248A3D',
  BACKGROUD_GREY_COLOR: '#97D0A533',
  BORDER_GREY_COLOR: '#D6D6D6',
  BLUE_COLOR: '#0077B6',
  DARK_BLACK: '#101828',
  COLOR_BORDER: '#2196F3',
  TRANSPARENT_BACKGROUNG: 'rgba(211, 211, 211, 0.4)',
  TRANSPARENT: 'transparent',
  SEARCH_TEXT_COLOR: '#9E9E9E',
  //
  LIGHT_RED: '#07CE6F',
  LIGHT_GREY: '#CACACA',
  BG_LIGHT: '#FAFAFA',
  DISABLE: '#E6E6E6',
  BG_LIGHT_TRANSPARENT: '#1D1A0CCC',
};

const images = {
  scanner: require('../../images/scanner.png'),

  // cource screen Icon
  golfPoint: require('../../images/golfPoint.png'),
  golfPinShot: require('../../images/golfPinShot.png'),
  Add: require('../../images/Add.png'),
  Remove: require('../../images/delete.png'),
  delete: require('../../images/delete.png'),
  splashBG: require('../../images/splash-background.png'),
  splashLogo: require('../../images/splash-items.png'),
  loginBG: require('../../images/bg5.png'),
  loginLogo: require('../../images/acecamlogo.png'),
  menu: require('../../images/menu.png'),
  logo: require('../../images/logo.png'),
  SplashScreen: require('../../images/backgroungimg.png'),
  Nodatafound: require('../../images/Nodatafound.png'),
  communitybg: require('../../images/communitybg.png'),
  Success: require('../../images/success.png'),
  house: require('../../images/house.png'),
  user: require('../../images/userimg.png'),
  golfVedio: require('../../images/golfVedio.png'),
  dropDown: require('../../images/dropdown.png'),
  // usgaGhin: require('../../images/USGA.png'),
  // golfTrophy: require('../../images/trophy.png'),

  trophy: require('../../images/trophy.png'),

  golfVedio: require('../../images/golfVedio.png'),
  closeIcon: require('../../images/close.png'),
  // video: '../../images/video.mp4',
  chalisa: require('../../images/chalisa.png'),
  pujapath: require('../../images/pujapath.png'),
  stotra: require('../../images/stotra.png'),
  stuti: require('../../images/stuti.png'),
  vidhi: require('../../images/vidhi.png'),
  bhakti: require('../../images/bhakti.png'),
  aarti: require('../../images/aarti.png'),
  googlelogo: '../../images/glogo.png',
  instagramlogo: '../../images/ilogo.png',
  Instagram: '../../images/Instagram.png',
  twitter: '../../images/twitter.png',
  Facebook: '../../images/Facebook.png',
  TikTok: '../../images/TikTok.png',
  Google: '../../images/Google.png',
  LogoScan: '../../images/LogoScan.png',

  //Home Screen Icons
  LeftCourceImg: require('../../images/LeftCourceImg.png'),
  backIconHeader: require('../../images/backIconHeader.png'),

  //enter queue screen images
  playerCover: require('../../images/playerCover.png'),
  backgroundGolf: require('../../images/backgroundGolf.png'),
  sports_golf: require('../../images/sports_golf.png'),

  holeInOne: require('../../images/holeInOne.png'),
  backButton: require('../../images/backButton.png'),
  submitScore: require('../../images/submitScore.png'),
  skipButton: require('../../images/skipButton.png'),

  //
  achievementBadge: require('../../images/achievementBadge.png'),
  holeOne: require('../../images/holeOne.png'),
  publishIcon: require('../../images/publishIcon.png'),
  menuIcon: require('../../images/menuIcon.png'),
  lockIcon: require('../../images/lockIcon.png'),
  requestVedioIcon: require('../../images/requestVedioIcon.png'),
  pendingRequest: require('../../images/pendingRequest.png'),
  re_Request: require('../../images/re-request-icon.png'),

  ball: require('../../images/ball.png'),

  Button_cancel: require('../../images/Button_cancel.png'),
  button_Request: require('../../images/button_Request.png'),
  
  icon_delete: require('../../images/icon_delete.png'),
  Button_No: require('../../images/Button_No.png'),
  logoBuddha: require('../../images/b10.png'),
  Button_Yes: require('../../images/Button_Yes.png'),
};

const NAVIGATION = {
  TO_LOGIN: 'Login',
  TO_EDIT_PROFILE: 'EditProfile',
  TO_PROFILE: 'EditProfile',
  TO_FORGET_PASSWORD: 'Verifyemail',
  TO_SIGNUP: 'Signup',
  TO_OTP_SCREEN: 'otp',
  TO_CHANGE_PASSWORD: 'Changepassword',
  TO_SUCCESS_SCREEN: 'SuccessScreen',
  TO_HOME: 'Home',
  TO_QUEUESCREEN: 'EnterQue',
  TO_COURSE_DETAIL: 'CourceDetails',
  TO_COURSECART: 'CourceCart',
  TO_PLAYINGCART: 'PayingCart',
  TO_COURSESCREEN: 'CourseScreen',

  TO_NOTIFICATION: 'Notification',
  TO_HOME_SCREEN: 'HomeScreen',
  TO_COURCE_CART: 'CourceCart',
  TO_COURCE_DETAIL: 'CourceDetails',
  TO_BET_CENTRAL: 'BetCentral',
  TO_HOME_DASHBOARD: 'HomeDashBoard',
  TO_TEEBOX_SCREEN: 'TeeBoxScreen',
  TO_HIT_THE_GREEN: 'HitTheGreen',
  TO_RECORD_RESULTS: 'RecordResults',
  TO_COUNTDOWN_BOX: 'CountdownBox',
  TO_PAYING_CART: 'PayingCart',
  TO_DASHBOARD: 'Dashboard',
  TO_COMMUNITY: 'Community',
  TO_MAIN: 'Main',
};

const API_CONSTANTS = {
  AC: 'AC',
};

const APP_TEXT = {
  // RESET PASSWORD OTP SCREEN - otp.js
  SPLASH_TEXT: 'Capturing Golf’s Greatest Shots',
  SPLASH_APP_NAME: 'AceCam',

  RESET_YOUR_PASSWORD: 'OTP Verification',
  OTP_SENT_TO: 'Enter the OTP sent to ',
  OTP_VALID_FOR: 'OTP is valid for 5 minutes',
  DIDNT_RECIEVE_OTP: 'Didn’t you receive the OTP? ',
  RESEND_OTP: 'Resend OTP',
  VERIFY_BUTTON: 'Verify Email',
  BACK_TO_LOGIN: 'Back to Login',
  YOU_CAN_RESEND_OTP: 'You can resend OTP in',
  SECONDS: 'seconds',
  HOME: 'Home',
  COMMUNITIES: 'Communities',
  USER:'Users',
  CONTESTS: 'Contests',
  BET_CENTRAL: 'Central',
  COURSE: 'Course',
  COMMUNITY: 'Community',
  PROFILE: 'Profile',
  PLAY: 'Play',
  SPLASH_TEXT: 'Capturing Golf’s Greatest Shots',
  SPLASH_APP_NAME: 'AceCam',

  // LOGIN SCREEN - login.js
  LOGIN_OR: '- OR -',
  LOGIN_USERNAME: 'Username',
  LOGIN_PASSWORD: 'Password',
  LOGIN_REMEMBER_ME: 'Remember Me?',
  LOGIN_CONFIRM_PASSWORD: 'Confirm Password',
  LOGIN_LOGIN: 'Login',
  LOGIN_DONT_HAVE_AN_ACCOUNT: 'Don’t have an account? ',
  LOGIN_SIGNUP: 'Sign Up',
  LOGIN_FORGET_PASSWORD: 'Forgot Password',
  SEND_OTP: 'Send OTP',

  // RESET PASSWORD SCREEN - Verifyemail.js
  RESET_PASSWORD: 'Forgot Your Password',
  RESET_YOUR_PASSWORD: 'Reset Your Password',
  EMAIL_PLACEHOLDER: 'Enter Registered Email Id',
  RESET_BUTTON: 'Reset Password',
  SUCCESS: 'SUCCESS',
  PASSWORD_CHANGED: 'Password Changed',

  // REGISTER SCREEN - signup.js
  FIRST_NAME: 'First Name',
  LAST_NAME: 'Last Name',
  USER_NAME: 'Username',
  CONFIRM_PASSWORD: 'Confirm Password',
  DATE_OF_BIRTH: 'Date of Birth',
  EMAIL: 'Email',
  PHONE: 'Phone',
  GHIN: 'GHIN',
  CARD_INFORMATION: 'Card Information',
  CARD_NUMBER: 'Card Number',
  EXPIRE_DATE: 'Expiry Date',
  CVV: 'CVV',
  NAME_ON_CARD: 'Full Name On Card',
  AGREEING_TO: 'Agreeing to',
  TERMS_AND_CONDITION: ' Terms and Conditions',
  OF_THE_CONTEST: ' of the contest',
  CREATE_ACCOUNT: 'Create Account',
  ALREADY_HAVE_ACCOUNT: 'Already have an account?',

  TEES: 'Tees',
  HOLES: 'Holes',
  ACTIVE: 'Active',
  SEARCH: 'search',
  CHECKOUT: 'Checkout',
  REGISTER: 'Register',
  REGISTER_ON_ONE_TEE_AT_A_TIME:
    'You can only register for contests from one tee at a time.',
  MINUS: 'minuscircle',
  PLUS: 'pluscircle',
  DOWN: 'down',
  RIGHT: 'right',
  HOLE_HASHTAG: 'Hole #',
  PAR: ' - Par ',
  CART_: 'cart',
  PLAYING_CART: 'Playing Cart',
  PAYMENT_METHOD: 'Payment Method',
  CHECK_OUT: 'Check Out',

  VIEW_PROFILE: 'ViewProfile',
  NO_PLAYER_FOUND: 'No User Found',
  COMMUNITIES: 'Communities',
  PLAYER_SEARCH: 'Player Search',

  //MODAL SCREEN 6
  ACHIEVEMENT_UNCLOCK: 'You’ve unlocked new \n      Achievements!',
  CLOSE: 'Close',

  //MODAL SCREEN 5
  ACHIEVEMENT_UNCLOCK: 'You’ve unlocked new \n      Achievements!',
  NEXT: 'Next',
  HIGHLIGHT_HUB: 'Highlight hub',
  ACCESS_VEDIO:
    'You now have access to request the video footage of your tee shot. Visit the',
  THAKS_FOR_RECORDING: 'Thank you for recording your results.',
  HIT_THE_GREEN: '[HIT THE GREEN]',

  //MODAL SCREEN 4
  FIRST_RANK_MSG: 'Wait, you got a Hole-in-One?! If so, click below.',
  SECOND_RANK_MSG: 'Birdie? Hell Yeah',
  THIRD_RANK_MSG: 'Par? Nice Hole',
  FOURTH_RANK_MSG: 'Bogey? Dang.',
  FIGTH_RANK_MSG: 'Double Bogey? Ouch.',
  SIXTH_RANK_MSG: 'Triple Bogey? Whoa.',
  PLACEHOLDER_SCORE: 'Score *',
  ENTER_SCORE: 'What happened next? \n      Enter your score...',
  GREAT_SHOT: 'Great Shot',

  //MODAL SCREEN 3
  SUBMIT_PROXIMITY: 'Submit Proximity',
  RULE_POINT:
    '(1) your shot is the closest to the pin in your group \n(2) you would like to track your stats either way',
  RULE_MSG:
    'Now use the measuring tape near the green and enter your proximity to the hole if... \n',
  GREEN_REGULATION: 'Green in Regulation!',

  //MODAL SCREEN 2
  BTN_MISSED_GREEN: 'Missed the Green',
  BTN_RECORD_RESULTS: 'Record your results',
  BTN_HIT_THE_GREEN: 'Hit the Green',
  //MODAL SCREEN 1
  BTN_MISSED_GREEN: 'Missed the Green',

  //MODAL
  NOTE: 'If it is unclear whether or not you hit the green, don’t worry, you can always go back and edit your results.',
  RECORD_MY_RESULT: 'Record My Results',
  DID_YOU_HIT: 'Did you hit the green?',
  BEFORE_NEXT_PLAYER: 'before the next player in the queue can hit',
  TO_HIT_GREEN: 'to hit your eligible tee shot and',
  MINUTES: 'minutes',
  YOU_ARE_ON_TEE: ' , you’re on the tee!',

  //TEESCREEN.JS
  MOVE_BUTTON: 'Move',
  READY_TO_HIT: 'YES, I’M READY TO HIT',
  MAKE_SURE_GREEN_CLEAR: 'Make sure the Green is clear!',
  PLAYER_IN_QUEUE: 'Players in Queue:',
  THE_TEE_BOX_OPEN: 'The Tee Box should be Open',
  UNTIL_THE_NEXT: 'until the next player can hit their tee shot.',
  RULE_TXT: ' to qualify for all contests and challenges, and you have',
  RULE_TXT1:
    'Once you confirm you’re ready to hit, your tee shot must be taken within',
};

export {colors, images, APP_TEXT, NAVIGATION, API_CONSTANTS};
